### ISSUE TITLE
Artifacts in unpacked PCX images

### ISSUE THREAD

**Issue by ChristopherRotter** [monkape/homm3-unpacker#2]
Some data returned by `unpackPCX` shows artifacts - transparency where there should be none. For example, this is a section of the unpacked file **CmBkSub.pcx** :

![image](https://user-images.githubusercontent.com/22773036/94555085-566a0400-025b-11eb-85a0-5a3f4212573b.png)

I haven't looked into the implementation details, perhaps there is an easy fix to it?

**Comment by monkape** [comment]
Thanks for reporting!

I have identified the issue, it is indeed a trivial fix I'll take care of when I find the time.

**Comment by monkape** [comment]
I've looked into this a bit deeper and wanted to share my findings.

### Source code

The code treats the first palette entry of PCX/DEF files as transparent pixels, so this is the line that causes the artifacts:
https://github.com/monkape/homm3-unpacker/blob/9574c88d766d74999e0ec4f36db5ab53e3428129/lib/unpackPCX.js#L38

### Game files analysis 

After an analysis of PCX/DEF files used by the game, it turns out that _not all_ of them are meant to support transparency. While the game possibly deals with such special cases in a hardcoded manner based on their filenames, this library parses files solely on binary data making such checks impossible.

I have identified three colours that represent transparency if they are the first entry in a PCX's palette:

- cyan `rgb(0,255,255)` - used by 4989 files
- magenta `rgb(255,0,255)` - used by 3 files
- black `rgb(0,0,0)` - used by 5 files
- other colours - used by 16 files (all combat backgrounds + `PuzzLogo.pcx` from `H3ab_bmp.lod`)

I believe all DEFs support transparency, regardless of what colour starts the palette. Anyway, DEF stats are:

- cyan `rgb(0,255,255)` - used by 2559 files
- almost cyan `rgb(0,254,255)` - used by 2 files (`C0acid.def` in both `H3sprite.lod` and `H3ab_spr.lod`)
- magenta `rgb(255,0,255)` - used by 2 files
- black `rgb(0,0,0)` - used by 3 files

Note that even if an image supports transparency, it doesn't necessarily have to use it.

### Solution

This library will solve the problem by supporting an array of rgb colours that are converted to transparent pixels if they are the first entry in the palette. Something along these lines:

```js
// defaults
unpackPCX(buffer)
unpackPCX(buffer, {
   transparency: [{r:0,g:255,b:255}, {r:255,g:0,b:255}, {r:0,g:0,b:0}]
})

// use red for transparency
unpackPCX(buffer, {
   transparency: [{r:255,g:0,b:0}]
})

// disable transparency; keep source colours
unpackPCX(buffer, {
   transparency: []
})
```

While there might be similarities between DEF's animation frames and PCX standalones, I will for now keep their implementations separate and assume that DEF's must support transparency. If they should at some point become merged and both support `.transparency`, the default colours must be expanded to additionally include `rgb(0,254,255)`.

-----

Note that only references to the recognised colour **at index 0** will work; in other words, a PCX can use the same colour for transparency and in image data:

```js
palette[0] = {r:0,g:255,b:255}    // treated as transparency
palette[1] = {r:0,g:255,b:255}    // treated as cyan

**Comment by ChristopherRotter** [comment]
Thanks for the detailed insight, much appreciated. Are you going to implement it yourself? Alternatively, I could open another PR for it in due time, but it's not an urgent matter for me.

**Comment by monkape** [comment]
Implemented in https://github.com/monkape/homm3-unpacker/commit/9bd2ef243e9623078458f4e363adad5090bf5a83.
